2021-02-16 00:40:59,612 ERROR: Exception on /index [GET] [in /home/purplerain/Documents/python/flask/test/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/purplerain/Documents/python/flask/test/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/purplerain/Documents/python/flask/test/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/purplerain/Documents/python/flask/test/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/purplerain/Documents/python/flask/test/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/purplerain/Documents/python/flask/test/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/purplerain/Documents/python/flask/test/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/purplerain/Documents/python/flask/test/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/purplerain/Documents/python/flask/blog/app/routes.py", line 33, in index
    return render_template('index.html', title='Home', form=form, posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "/home/purplerain/Documents/python/flask/test/venv/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/purplerain/Documents/python/flask/test/venv/lib/python3.8/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/purplerain/Documents/python/flask/test/venv/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/purplerain/Documents/python/flask/test/venv/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/purplerain/Documents/python/flask/test/venv/lib/python3.8/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/purplerain/Documents/python/flask/test/venv/lib/python3.8/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/purplerain/Documents/python/flask/test/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/purplerain/Documents/python/flask/test/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/purplerain/Documents/python/flask/blog/app/templates/index.html", line 27, in template
    {% endblock
jinja2.exceptions.TemplateSyntaxError: unexpected end of template, expected 'end of statement block'.
2021-02-16 00:41:23,320 INFO: Microblog startup [in /home/purplerain/Documents/python/flask/blog/app/__init__.py:48]
2021-02-16 00:48:41,857 INFO: Microblog startup [in /home/purplerain/Documents/python/flask/blog/app/__init__.py:48]
2021-02-16 00:51:30,357 INFO: Microblog startup [in /home/purplerain/Documents/python/flask/blog/app/__init__.py:48]
2021-02-16 00:54:18,632 INFO: Microblog startup [in /home/purplerain/Documents/python/flask/blog/app/__init__.py:48]
2021-02-16 00:55:34,937 INFO: Microblog startup [in /home/purplerain/Documents/python/flask/blog/app/__init__.py:48]
2021-02-16 16:04:04,722 INFO: Microblog startup [in /home/purplerain/Documents/python/flask/blog/app/__init__.py:48]
2021-02-16 16:15:07,185 INFO: Microblog startup [in /home/purplerain/Documents/python/flask/blog/app/__init__.py:50]
2021-02-17 14:50:11,037 INFO: Microblog startup [in /home/purplerain/Documents/python/flask/blog/app/__init__.py:50]
